# Generated by Django 3.1.1 on 2020-09-17 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_user'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecomment',
            name='original_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='recipedislike',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dislike', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='recipelike',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='recipes.recipe'),
        ),
    ]
