# Generated by Django 3.1.1 on 2020-09-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='quantity_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
